### ISSUE TITLE
We plan to feature your VS Code extension!

### ISSUE THREAD

**Issue by auchenberg** [DonJayamanne/vscodeJupyter#108]
Hi,

It's Kenneth from VS Code. I'm reaching out to tell you that we plan to feature your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode in the next iteration. I'm opening an issue here as there seem to many contributors on this extension, and I'm not sure who the rightful owner is.

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding! 

/k

------
Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by DonJayamanne** [comment]
I'm the owner of this extension. Awesome looking forward to this.

**Comment by osya** [comment]
@auchenberg , if you interested in this extension, then why you (VS Code development team) duplicated some functionality from this extension in the [vscode-python:](github.com/Microsoft/vscode-python:)? Conflicting commands which exists in both extensions: `runSelectionLine`, `execCurrentCell`, `execCurrentCellAndAdvance`, `gotToPreviousCell`, `gotToNextCell`

**Comment by DonJayamanne** [comment]
@osya
I authored both extensions.
Jupyter was removed from the Python extension as it didn't make sense leaving it in there ( it wasn't a python specific feature applied to other languages as well).

I guess it's time to remove those warning messages now.

The commands were left in there so that people people who upgraded to just python extension will get a message informing them to install the Jupiter extension.
